### PR TITLE
Make the weight parameter adjustable

### PR DESCRIPTION
**Pull request by zdenop**
- Make the weight parameter adjustable
- Update docs

### CODE REVIEW

**Comment by DanBloomberg** [comment]
Looks fine to me.

Is it possible to acknowledge [zvezdochiot](https://github.com/zvezdochiot) and capture some of his tests (at least saving the commands)?

**Comment by zvezdochiot** [comment]
@DanBloomberg say:
>(at least saving the commands)?

Only a separate turnip, for example `jbig2enc-demo` or `jbig2enc-samples`. Don't clutter the main repo with any extraneous junk.

**Comment by DanBloomberg** [comment]
I agree -- it's a good idea to keep jbig2enc uncluttered and as lean as possible.

Dan

**Comment by zdenop** [comment]
I made zvezdochiot the author of the commit. @zvezdochiot : will you create example repo within ImageProcessing-ElectronicPublications?

**Comment by zvezdochiot** [comment]
@zdenop say:
>will you create an example repo within ImageProcessing-ElectronicPublications?

This is an extremely controversial issue. Here, the author must express his opinion on how the documentation should be organized.

For example, he can say: “I myself organize `jbig2enc-demo`, I trust @zdenop to organize `jbig2enc-samples`, and @zvezdochiot - `jbig2enc-minidjvu`”.

We have to wait to see what the author says.

**Comment by zdenop** [comment]
Author (agl) is not active here anymore - he just gave Dan and me limited access to this repo, so we can maintain it.

**Comment by zvezdochiot** [comment]
@zdenop say:
>Dan and me limited access to this repo, so we can maintain it.

Ok. I've added a description of my recipe to [jbig2enc-minidjvu](https://github.com/ImageProcessing-ElectronicPublications/jbig2enc-minidjvu) and will add test materials soon.

Good luck. :smile:

**Comment by DanBloomberg** [comment]
Thank you for all your help!

**Pull request merged**
